version: '3.8'

services:
  web-avance-db:
    image: mysql:8.0
    volumes:
      - web-avance-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web
    networks:
      - web-avance-network
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password


  web-avance-api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    depends_on:
      - web-avance-db
    networks:
      - web-avance-network
    environment:
      DB_NAME: web
      DB_HOST: web-avance-db
      DB_TYPE: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      JWT_SECRET: jwt-secret
    restart: always


networks:
  web-avance-network:
    driver: bridge

volumes:
  web-avance-db: